### ISSUE TITLE
ToDo: Brush/Primitive creation

### ISSUE THREAD

**Issue by ashifolfi** [ashifolfi/Chisel#1]
ToDo for the brush/primitive system:

- [x] *Creation of an object programmatically
- [ ] *Ability to move and resize primitives
- [x] *Proper UV mapping for primitives (Required for texture support)
- [x] Proper Normal mapping for primitives (Required for planned lighting preview/shaded 3d view)
- [ ] Add shapes other than a cube
- [ ] *Face specific textures
- [x] *Add ability to delete meshes

Not all of these features are required for a Proof of Concept release of Chisel. Only entries marked with a * are needed

**Comment by ashifolfi** [comment]
One thing that I'm not the best at still is things like uv mapping. so if someone could help get the UV mapping to work consistently across all of the faces that would be very nice!

**Comment by ashifolfi** [comment]
update: my dumbass didn't realize you could `CubeMesh.new()` so uh commit coming soon containing a complete overhaul of the primitive creation system using existing godot primitive meshes

**Comment by ashifolfi** [comment]
#8 is a requirement for this to be closed
